### ISSUE TITLE
[BUG] SetProviderIdsFromPath no longer works

### ISSUE THREAD

**Issue by roblav96** [MediaBrowser/Emby.Naming#13]
**Description:**
Digging through the source code I came across:
[`SetProviderIdsFromPath`](https://github.com/MediaBrowser/Emby/blob/e4f1a16550f7d497968d19683812e594785fbcd9/Emby.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs#L333) and [`GetAttributeValue`](https://github.com/MediaBrowser/Emby/blob/master/Emby.Server.Implementations/Library/PathExtensions.cs#L15)
which resolves the provider ids (`imdbid`, `tmdbid`) from the item's `Path`.

**Example:**
`~/Emby/Movies/Pulp Fiction (1994) [imdbid=tt0110912] [tmdbid=680].strm`

**Problem:**
Recently since upgrading `MovieDb@1.1.1.0` plugin this method of resolving provider ids no longer works.

**Proof:**
The logs while scanning library
`Info App: MovieDbProvider: Finding id for item: Pulp Fiction`
whereas before, this extra step would never take place.

**Environments:**
```
# Mac OSX 10.13.6
Info Main: Emby
    Command line: /Applications/EmbyServer.app/Contents/MacOS/EmbyServer.dll
    Operating system: Unix 17.7.0.0
    64-Bit OS: True
    64-Bit Process: True
    Processor count: 8
Info App: Application version: 4.1.1.0
```
```
# Ubuntu Server 19.04 LTS
Info Main: Emby
    Command line: /opt/emby-server/system/EmbyServer.dll
    Operating system: Unix 5.0.0.13
    64-Bit OS: True
    64-Bit Process: True
    Processor count: 16
Info App: Application version: 4.2.0.5
```
Both environments have this problem.

**Comment by LukePulverenti** [comment]
Why closing? I had not had a chance to look at this yet. Thanks.

**Comment by LukePulverenti** [comment]
@roblav96 just curious, any comments?

**Comment by roblav96** [comment]
@LukePulverenti Hey sorry about the delay.

It seems to only happen on `TV Shows` library when `TheTVDB` has first priority for series metadata. I no longer use that configuration order which is why I closed it.

**Comment by LukePulverenti** [comment]
Ok, i did a quick test and could not reproduce. What i mean is that the id's specified in the path were preserved. I'll keep an eye on this though. Thanks.

**Comment by LukePulverenti** [comment]
I see you are pretty seasoned with JavaScript? If you're interested in work then please contact me privately on the Emby community. Thanks.
