### ISSUE TITLE
The type "ILogger" is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by Medisex64** [MediaBrowser/Emby.Naming#7]
I installed `MediaBrowser.Naming` through Nuget, but when I try to build my project it fails. The assembly `MediaBrowser.Model` is the latest version being 3.0.647 but Visual Studio tells me I need to reference a 3.1 version of the library.

**Comment by wcapes21** [comment]
+1, if anyone has a fix please let me know.

**Comment by LukePulverenti** [comment]
It's resolved now. Make sure you're running Visual Studio 2017. thanks.
